### ISSUE TITLE
(FunctionClauseError) in master

### ISSUE THREAD

**Issue by zllovesuki** [tmate-io/tmate-master#4]
Log from Kubernetes:

```
2020-03-15T11:22:00.001786074Z 11:22:00.001 [info] Checking for disconnected sessions
2020-03-15T11:22:00.001822426Z 11:22:00.001 [info] Pruning dead sessions older than 1 week
2020-03-15T11:22:00.091545475Z 11:22:00.091 [error] Task #PID<0.3345.0> started from #PID<0.3343.0> terminating
2020-03-15T11:22:00.091576961Z ** (FunctionClauseError) no function clause matching in Access.get/3
2020-03-15T11:22:00.091581334Z     (elixir) lib/access.ex:265: Access.get("{\"stale_ids\":[]}", "stale_ids", nil)
2020-03-15T11:22:00.091585115Z     (tmate) lib/tmate/ws_api.ex:11: Tmate.WsApi.get_stale_sessions/2
2020-03-15T11:22:00.091588367Z     (tmate) lib/tmate/session_cleaner.ex:58: Tmate.SessionCleaner.check_for_disconnected_sessions/2
2020-03-15T11:22:00.09159162Z     (elixir) lib/enum.ex:789: anonymous fn/3 in Enum.each/2
2020-03-15T11:22:00.091594817Z     (stdlib) maps.erl:232: :maps.fold_1/3
2020-03-15T11:22:00.091597854Z     (elixir) lib/enum.ex:1964: Enum.each/2
2020-03-15T11:22:00.091600817Z     (tmate) lib/tmate/session_cleaner.ex:35: Tmate.SessionCleaner.check_for_disconnected_sessions/0
2020-03-15T11:22:00.091603937Z     (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
2020-03-15T11:22:00.091606992Z Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
2020-03-15T11:22:00.091610313Z     Args: []
```

Running the docker image from the lastest commit 5a309054e9888bc3a7b0db7d6d67ecc6a3cca526

Database was populated via:
```
MIX_ENV=prod PG_URI='postgres://[redacted]' PG_POOLSIZE=1 mix ecto.migrate
````

**Comment by nviennot** [comment]
Hmm, very strange. It looks like the JSON parsing is not working. It should, based on lib/tmate/ws_api.ex:7

**Comment by kovacs-andras** [comment]
I'm facing the same issue.
